version: 2.1
executors:
  node-executor:
    docker:
      - image: cimg/node:18.20.2
    working_directory: ~/project
jobs:
  test-playwright:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
            - npm-cache-
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - run:
          name: Install Playwright Browsers
          command: npx playwright install --with-deps
      - run:
          name: Create Playwright config to use root directory
          command: |
            echo "module.exports = { testDir: '.' }" > playwright.config.js
      - run:
          name: Run Playwright tests
          command: npx playwright test
      - store_artifacts:
          path: test-results
          destination: test-results
workflows:
  version: 2
  test:
    jobs:
      - test-playwright