version: 2.1
executors:
  node-executor:
    docker:
      - image: cimg/node:18.20.2
    working_directory: ~/project
jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
            - npm-cache-
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - run:
          name: Build the project
          command: npm run build
      - store_artifacts:
          path: dist
          destination: dist
workflows:
  version: 2
  build-and-store:
    jobs:
      - build
