// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jiysvnkeuzxvjsgcjrid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppeXN2bmtldXp4dmpzZ2NqcmlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1ODEyNjUsImV4cCI6MjA2MTE1NzI2NX0.EDZ8Ct6HF4TERtEn2ac3C8minKqhCJkCbnh9JV8q4VQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);